version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - pip3 install -q awscli --upgrade --user
      - yum -q install -y jq
  build:
    commands:
      - zip campaign_service.zip ./campaign_service/__init__.py ./campaign_service/welcome-mail.py
  post_build:
    commands:
      - aws s3 cp campaign_service.zip  s3://ecom-email-sourcecode-bucket/campaign_service.zip
      - aws lambda update-function-code --function-name ${env}-e-commerce_business-campaign-service --s3-bucket ecom-email-sourcecode-bucket --s3-key campaign_service.zip
     h
      